// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdCfU2zIMCN46oZFPX1drUYPps85zSXsU',
    appId: '1:620346958331:web:37a7c97922906e6c616b5e',
    messagingSenderId: '620346958331',
    projectId: 'to-do-e37dc',
    authDomain: 'to-do-e37dc.firebaseapp.com',
    storageBucket: 'to-do-e37dc.appspot.com',
    measurementId: 'G-NJX9KHGF59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqAXmV1GL5HojusNw92qrfUht6WD_8yGY',
    appId: '1:620346958331:android:321fc0d3396e5c89616b5e',
    messagingSenderId: '620346958331',
    projectId: 'to-do-e37dc',
    storageBucket: 'to-do-e37dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTlxvPp9MZ_9GgBS2ZHsO0pIy0jYjoQRs',
    appId: '1:620346958331:ios:a7abde23b425bff4616b5e',
    messagingSenderId: '620346958331',
    projectId: 'to-do-e37dc',
    storageBucket: 'to-do-e37dc.appspot.com',
    iosClientId: '620346958331-354qhprpfeo30e17bpga5kgm9ro3g6mu.apps.googleusercontent.com',
    iosBundleId: 'com.app.todo.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTlxvPp9MZ_9GgBS2ZHsO0pIy0jYjoQRs',
    appId: '1:620346958331:ios:a7abde23b425bff4616b5e',
    messagingSenderId: '620346958331',
    projectId: 'to-do-e37dc',
    storageBucket: 'to-do-e37dc.appspot.com',
    iosClientId: '620346958331-354qhprpfeo30e17bpga5kgm9ro3g6mu.apps.googleusercontent.com',
    iosBundleId: 'com.app.todo.todoApp',
  );
}
